--First I ran this select to see the diff between price list & UPC data

SELECT DISTINCT a.Name, b.Final_Pattern_name
FROM tbl_RawData_FW13_MER_FOOT_UPC AS a
FULL JOIN tbl_RawData_FW13_MER_FOOT_Price_List AS b
ON a.Name = b.Final_Pattern_name

--Two styles were present on the price list but not in the UPC data. I have asked Ben H. about them.
--Several other styles did not match initially, so I manually updated the UPC data to conform to the price list naming conventions
--Now I can perform this join for my simples section:

SELECT DISTINCT
	...
FROM tbl_RawData_FW13_MER_FOOT_UPC AS a 
INNER JOIN tbl_RawData_FW13_MER_FOOT_Price_List AS b 
ON a.Name = b.Final_Pattern_name

--I could use the name as vendor_product_id, but that's sloppy, so I added the STYLENUMBER column to tbl_RawData_FW13_MER_FOOT_Price_List and ran this SELECT:

SELECT DISTINCT (SELECT SUBSTRING(CONVERT(varchar(40), NEWID()),0,6)) AS STYLENUMBER,Final_Pattern_name
FROM tbl_RawData_FW13_MER_FOOT_Price_List

--I then copied the output into TextMate and performed some Find & Replaces to generate this UPDATE block:

UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '1A156' WHERE Final_Pattern_name = 'Agama'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = 'B5B04' WHERE Final_Pattern_name = 'Amaryllis'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '4FCB1' WHERE Final_Pattern_name = 'Arctic Fox 6 Waterproof'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '4AA6D' WHERE Final_Pattern_name = 'Arctic Fox 8 Waterproof'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = 'DF3A2' WHERE Final_Pattern_name = 'Arctic Fox Moc Waterproof'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '94DA0' WHERE Final_Pattern_name = 'Ascend Glove'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '70279' WHERE Final_Pattern_name = 'Avesso'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '43520' WHERE Final_Pattern_name = 'Avian Light Convertible'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '653D5' WHERE Final_Pattern_name = 'Avian Light Flip'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = 'C1E25' WHERE Final_Pattern_name = 'Avian Light LTR'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '5CAED' WHERE Final_Pattern_name = 'Avian Light Mid WTPF'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = 'D6A58' WHERE Final_Pattern_name = 'Avian Light Strap'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '160FF' WHERE Final_Pattern_name = 'Avian Light Vent WTPF'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = 'D1111' WHERE Final_Pattern_name = 'Avian Light Ventilator'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '823D1' WHERE Final_Pattern_name = 'Bare Access 2'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '02EAF' WHERE Final_Pattern_name = 'Bare Access Arc 2'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '947B9' WHERE Final_Pattern_name = 'Cambrian Strap Sport'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = 'D7C67' WHERE Final_Pattern_name = 'Captiva Emme'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = 'F7922' WHERE Final_Pattern_name = 'Captiva Lace'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = 'B3E81' WHERE Final_Pattern_name = 'Captiva Launch Waterproof'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '45A46' WHERE Final_Pattern_name = 'Captiva Mid Waterproof'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = 'FD115' WHERE Final_Pattern_name = 'Captiva Moc'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '00F9E' WHERE Final_Pattern_name = 'Captiva Slide'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = 'E7373' WHERE Final_Pattern_name = 'Captiva Strap Waterproof'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '57062' WHERE Final_Pattern_name = 'Cham 5 Mid Vent WTPF'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '597AC' WHERE Final_Pattern_name = 'Cham 5 Vent'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '9E44B' WHERE Final_Pattern_name = 'Cham 5 WTPF'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '5EE0B' WHERE Final_Pattern_name = 'Cham Arc Contender WTPF'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = 'DE394' WHERE Final_Pattern_name = 'Cham Arc Voyager Sport'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '03230' WHERE Final_Pattern_name = 'Chameleon 4 Mid Trek Wtpf Kids'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '48C0B' WHERE Final_Pattern_name = 'Chameleon 4 Mid Vent Kids'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = 'BC188' WHERE Final_Pattern_name = 'Chameleon 4 Vent Strap Kids'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '60353' WHERE Final_Pattern_name = 'Chameleon 4 Ventilator Kids'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '587E4' WHERE Final_Pattern_name = 'Chameleon Spin Waterproof Kids'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '010D9' WHERE Final_Pattern_name = 'Chameleon Thermo 6 W/P Synthc'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '2EE5D' WHERE Final_Pattern_name = 'Chameleon Thermo 8 W/P Syn'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '9B3C1' WHERE Final_Pattern_name = 'Chameleon Thermo 8 W/P Synthc'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = 'D891F' WHERE Final_Pattern_name = 'Circuit Access'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = 'D343E' WHERE Final_Pattern_name = 'Crush Glove'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = 'BF0FE' WHERE Final_Pattern_name = 'Crush Glove Kids'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '6355A' WHERE Final_Pattern_name = 'Cypher Glove'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '1BF88' WHERE Final_Pattern_name = 'Decora Chant WTPF'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '10B2B' WHERE Final_Pattern_name = 'Decora Minuet WTPF'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '13423' WHERE Final_Pattern_name = 'Decora Prelude WTPF'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '15322' WHERE Final_Pattern_name = 'Decora Sonata WTPF'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = 'EBED1' WHERE Final_Pattern_name = 'Encore Apex Waterproof'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '9FF88' WHERE Final_Pattern_name = 'Encore Blip'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '45A6F' WHERE Final_Pattern_name = 'Encore Nova Crystal '
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '72192' WHERE Final_Pattern_name = 'Encore Nova Crystal LTR'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = 'F228B' WHERE Final_Pattern_name = 'Encore Pleat Moc'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = 'AB0F6' WHERE Final_Pattern_name = 'Encore Pleat Slide'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '105F8' WHERE Final_Pattern_name = 'Evera Amp'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '44DB7' WHERE Final_Pattern_name = 'Evera Draft'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '49EE7' WHERE Final_Pattern_name = 'Evera Fade'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = 'BEFC8' WHERE Final_Pattern_name = 'Evera Rush'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '6BD5B' WHERE Final_Pattern_name = 'Excursion Glove'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '4CC03' WHERE Final_Pattern_name = 'Flux Glove'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = 'D43C0' WHERE Final_Pattern_name = 'Flux Glove Kids'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '74B85' WHERE Final_Pattern_name = 'Geomorph Blaze'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '6FF50' WHERE Final_Pattern_name = 'Geomorph Blaze Mid Thermo WTPF'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '68493' WHERE Final_Pattern_name = 'Geomorph Blaze Mid WTPF'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '61B94' WHERE Final_Pattern_name = 'Geomorph Blaze Waterproof'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '4AF08' WHERE Final_Pattern_name = 'Grasshopper Sport'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = 'CB279' WHERE Final_Pattern_name = 'Grasshopper Sport Mid WTPF'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '181D7' WHERE Final_Pattern_name = 'Grasshopper Sport WTPF'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = 'DE905' WHERE Final_Pattern_name = 'Haven Autumn WTPF'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '684F2' WHERE Final_Pattern_name = 'Haven Winter WTPF'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '93DCE' WHERE Final_Pattern_name = 'Himavat Chukka WTPF'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '2B679' WHERE Final_Pattern_name = 'Hollyleaf'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '81293' WHERE Final_Pattern_name = 'Hylox'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '1BFF3' WHERE Final_Pattern_name = 'Hyperbolic'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '84BD6' WHERE Final_Pattern_name = 'Iceclaw Mid WTPF'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '6B3CD' WHERE Final_Pattern_name = 'Immerse Mid WTPF'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '5E122' WHERE Final_Pattern_name = 'Jacardia'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '10DEC' WHERE Final_Pattern_name = 'Jungle Glove'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '21599' WHERE Final_Pattern_name = 'Jungle Moc'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '60BEF' WHERE Final_Pattern_name = 'Jungle Moc Frosty Wtpf Kids'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '95F0B' WHERE Final_Pattern_name = 'Jungle Moc Kids'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '9C051' WHERE Final_Pattern_name = 'Jungle Moc Leather'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = 'F97B4' WHERE Final_Pattern_name = 'Jungle Moc Leather Kids'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '15A54' WHERE Final_Pattern_name = 'Jungle Moc Nubuck'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = 'C9CC2' WHERE Final_Pattern_name = 'Lorelei Link'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '72944' WHERE Final_Pattern_name = 'Lorelei Twine'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = 'ABBAF' WHERE Final_Pattern_name = 'Lorelei Zip'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '89B62' WHERE Final_Pattern_name = 'Luxe Whip'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '22614' WHERE Final_Pattern_name = 'Mattertal Echo Gore-Tex'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '85417' WHERE Final_Pattern_name = 'Mattertal Gore-Tex'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '412E1' WHERE Final_Pattern_name = 'Mimosa Ginger'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = 'D85E3' WHERE Final_Pattern_name = 'Mimosa Glee'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '54068' WHERE Final_Pattern_name = 'Mimosa Harvest Waterproof Kids'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '98562' WHERE Final_Pattern_name = 'Mimosa Lace'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '4AFE3' WHERE Final_Pattern_name = 'Mimosa Moc'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '456CD' WHERE Final_Pattern_name = 'Mimosa Toggle Kids'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '99336' WHERE Final_Pattern_name = 'Mimosa Toggle Wtpf Kids'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '687A6' WHERE Final_Pattern_name = 'Mimosa Vex WTPF'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '6918B' WHERE Final_Pattern_name = 'Mix Master 2 WTPF'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '9442A' WHERE Final_Pattern_name = 'Mix Master Jam Kids'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '2C604' WHERE Final_Pattern_name = 'Mix Master Jam Z-Rap Kids'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = 'AB3FB' WHERE Final_Pattern_name = 'Mix Master Move'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '70EC1' WHERE Final_Pattern_name = 'Mix Master Move Glide'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = 'E3B99' WHERE Final_Pattern_name = 'Mix Master Tuff'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '85D83' WHERE Final_Pattern_name = 'Mix Master Tuff Mid WTPF'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = 'BBF52' WHERE Final_Pattern_name = 'Moab GTX'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = 'FF6ED' WHERE Final_Pattern_name = 'Moab Mid GTX'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '1FCF3' WHERE Final_Pattern_name = 'Moab Polar Mid Strap Wtpf Kids'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = 'E5846' WHERE Final_Pattern_name = 'Moab Polar WTPF'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '8EC7D' WHERE Final_Pattern_name = 'Moab Ventilator'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '7F57D' WHERE Final_Pattern_name = 'Mountain Diggs'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = 'C1827' WHERE Final_Pattern_name = 'Mountain Kicks'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '9E02E' WHERE Final_Pattern_name = 'Mountain Moc'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = 'CB9DC' WHERE Final_Pattern_name = 'Mountain Treads WTPF'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '1870F' WHERE Final_Pattern_name = 'Natalya Waterproof'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '59000' WHERE Final_Pattern_name = 'Nikita Waterproof'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = 'B53DE' WHERE Final_Pattern_name = 'Norsehund Alpha Waterproof'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '9F0EC' WHERE Final_Pattern_name = 'Norsehund Beta Waterproof'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = 'DAF86' WHERE Final_Pattern_name = 'Norsehund Omega Mid Waterproof'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = 'FB211' WHERE Final_Pattern_name = 'Olmec'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '7209E' WHERE Final_Pattern_name = 'Pace Glove 2'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '1F75E' WHERE Final_Pattern_name = 'Phaser Epic WTPF'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '9FEF7' WHERE Final_Pattern_name = 'Phoenix Trek'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '794E0' WHERE Final_Pattern_name = 'Phoenix Trek Mid WTPF'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '95EEA' WHERE Final_Pattern_name = 'Pivot Lace'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '7ED19' WHERE Final_Pattern_name = 'Plumeria'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '2B433' WHERE Final_Pattern_name = 'Prevoz Waterproof'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = 'BDC59' WHERE Final_Pattern_name = 'Proterra'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '6AA92' WHERE Final_Pattern_name = 'Proterra Frost Mid GTX'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '390BB' WHERE Final_Pattern_name = 'Proterra GTX'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '189DA' WHERE Final_Pattern_name = 'Proterra Mid GTX'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = 'FE235' WHERE Final_Pattern_name = 'Proterra Mid Sport GTX'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '9B3BA' WHERE Final_Pattern_name = 'Proterra Mid Waterproof Kids'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = 'B8507' WHERE Final_Pattern_name = 'Proterra Sport'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '22B43' WHERE Final_Pattern_name = 'Proterra Sport GTX'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = 'C80E0' WHERE Final_Pattern_name = 'Proterra Sport Kids'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = 'CDA35' WHERE Final_Pattern_name = 'Proterra Vim Sport'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '147A6' WHERE Final_Pattern_name = 'Radius Glove'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '5CDC9' WHERE Final_Pattern_name = 'Rant'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '87A9D' WHERE Final_Pattern_name = 'Rant Evo'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '2156B' WHERE Final_Pattern_name = 'Reach Glove'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '7F96B' WHERE Final_Pattern_name = 'Realm Lace'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = 'B6A4D' WHERE Final_Pattern_name = 'Realm Moc'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '6ADA6' WHERE Final_Pattern_name = 'Realm Pull'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = 'D313D' WHERE Final_Pattern_name = 'River Glove'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '79049' WHERE Final_Pattern_name = 'Road Glove 2'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '6ACA8' WHERE Final_Pattern_name = 'Road Glove Dash 2'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '0E5E0' WHERE Final_Pattern_name = 'Rosella Lace'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = 'E2E57' WHERE Final_Pattern_name = 'Rosella Truss'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '69FDD' WHERE Final_Pattern_name = 'Salida'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = 'BF0C2' WHERE Final_Pattern_name = 'Salida Mid WTPF'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = 'E3326' WHERE Final_Pattern_name = 'Salida Trekker'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '44E4E' WHERE Final_Pattern_name = 'Sector Pike'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '0DD70' WHERE Final_Pattern_name = 'Shiver Boot Waterproof'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = 'A3CF4' WHERE Final_Pattern_name = 'Shiver Moc 2 Waterproof'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '8DB6E' WHERE Final_Pattern_name = 'Sight'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '6F1A4' WHERE Final_Pattern_name = 'Siren Ginger'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = 'A2804' WHERE Final_Pattern_name = 'Siren Mid Thermo'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '36663' WHERE Final_Pattern_name = 'Siren Sport'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '1429B' WHERE Final_Pattern_name = 'Siren Sport GTX'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = 'C3EE3' WHERE Final_Pattern_name = 'Siren Surge'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = 'F80E6' WHERE Final_Pattern_name = 'Siren Ventilator'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = 'C67F6' WHERE Final_Pattern_name = 'Skylark'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '7B5ED' WHERE Final_Pattern_name = 'Snow Bank Waterproof Kids'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '239C9' WHERE Final_Pattern_name = 'Snowbound Drift Mid WTPF'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '337E0' WHERE Final_Pattern_name = 'Snowbound Mid Waterproof'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '35EF9' WHERE Final_Pattern_name = 'Snowhound Mid WTPF'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '1A587' WHERE Final_Pattern_name = 'Spellbound Peak'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '1A867' WHERE Final_Pattern_name = 'Spellbound Zip'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '8E40F' WHERE Final_Pattern_name = 'Spruzzi Wtpf Kids'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = 'B1891' WHERE Final_Pattern_name = 'Swirl Glove'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = 'CB04F' WHERE Final_Pattern_name = 'Tailgate'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '8CA86' WHERE Final_Pattern_name = 'Tailspin Toggle Kids'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '62E78' WHERE Final_Pattern_name = 'Tailspin Toggle Wtpf Kids'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '25558' WHERE Final_Pattern_name = 'Tegus'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '82DD2' WHERE Final_Pattern_name = 'Terrapin'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '46152' WHERE Final_Pattern_name = 'Thermo Arc 8 Waterproof'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '63BC4' WHERE Final_Pattern_name = 'Tour Glove'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = 'C16EF' WHERE Final_Pattern_name = 'Trail Glove 2'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '323A1' WHERE Final_Pattern_name = 'Trail Glove Kids'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '7AA02' WHERE Final_Pattern_name = 'Traveler Rove'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '9C21D' WHERE Final_Pattern_name = 'Traveler Sphere'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = 'B9B7E' WHERE Final_Pattern_name = 'Traveler Spin'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = 'B070B' WHERE Final_Pattern_name = 'Traveler Tour WTPF'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '87274' WHERE Final_Pattern_name = 'Tucson'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '091CD' WHERE Final_Pattern_name = 'Tucson WTPF'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '443C1' WHERE Final_Pattern_name = 'Twist Glove'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '44C3E' WHERE Final_Pattern_name = 'Vapor Glove'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '7BB12' WHERE Final_Pattern_name = 'Violotta'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '3CDB8' WHERE Final_Pattern_name = 'Waterpro Ganges'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = 'F56E7' WHERE Final_Pattern_name = 'Waterpro Gauley'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '8B5B5' WHERE Final_Pattern_name = 'Wedgetarian Lexi'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '34A40' WHERE Final_Pattern_name = 'Wedgetarian Lyla'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = 'AB8FA' WHERE Final_Pattern_name = 'Wonder Glove'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '5D71F' WHERE Final_Pattern_name = 'Zermatt Echo Sport Gore-Tex'
UPDATE tbl_RawData_FW13_MER_FOOT_Price_List SET STYLENUMBER = '88360' WHERE Final_Pattern_name = 'Zermatt Sport GTX'

--Then I added the STYLENUMBER column to tbl_RawData_FW13_MER_FOOT_UPC and ran this UPDATE to normalize the randomly generated vendor_product_id values:

UPDATE a SET
	a.STYLENUMBER = b.STYLENUMBER
FROM tbl_RawData_FW13_MER_FOOT_UPC AS a 
INNER JOIN tbl_RawData_FW13_MER_FOOT_Price_List AS b 
ON a.Name = b.Final_Pattern_name